export const USER_STATUS_NOT_AUTH = 'NOT_AUTH';
export const USER_STATUS_NO_PASSWORD = 'NO_PASSWORD';
export const USER_STATUS_NO_ETHADDRESS = 'NO_ETHADDRESS';
export const USER_STATUS_WAIT_MINT = 'WAIT_MINT';
export const USER_STATUS_WAIT_REFILL = 'WAIT_REFILL';
export const USER_STATUS_TOKENS_DELIVERED = 'TOKENS_DELIVERED';

export const TICKET_STATUS_NEW = 'NEW';
export const TICKET_STATUS_IN_WORK = 'IN_WORK';
export const TICKET_STATUS_REPLIED = 'REPLIED';
export const TICKET_STATUS_SOLVED = 'SOLVED';
export const TICKET_STATUS_CLOSED = 'CLOSED';

export const TICKET_MSG_STATUS_NEW = 'NEW';
export const TICKET_MSG_STATUS_VIEWED = 'VIEWED';
export const TICKET_MSG_STATUS_REPLIED = 'REPLIED';
export const TICKET_MSG_STATUS_DELETED = 'DELETED';
